title: Nahomi Cruz
description: Bitacora Wearables Nahomi Cruz

# GitHub Pages: modo recomendado
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# IMPORTANTES:
# - Para GitHub Pages (Project Page), edita:
#     url: "https://Nahomi_Cruz.github.io"
#     baseurl: "/NOMBRE_DEL_REPO"
url: "https://nahomimilk.github.io/"
baseurl: "/nahomi-cruz-wearables"

#Configuracion Formato, Header y Footer
just_the_docs:
  # incluir CSS adicional
  custom_css:
    - "assets/css/custom.css"
  footer_content: ""

search_enabled: true
search:
  # Cambia el numero dependiendo el numero de subniveles de p√°ginas, poner 1 por default
  heading_level: 2

# Ejemplo de enlace auxiliar (aparece arriba a la derecha)
aux_links:
  "Repositorio en GitHub":
    - "https://github.com/nahomimilk/nahomi-cruz-wearables"

# Enlaces
permalink: pretty

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor"
